apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kubegame
spec:
  customresourcedefinitions:
    owned:
    - kind: Game
      name: games.kubegame.systemcraftsman.com
      version: v1alpha1
  displayName: kubegame
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - kubegame.systemcraftsman.com
          resources:
          - games
          - games/status
          - games/finalizers
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - create
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
        serviceAccountName: kubegame-operator
      deployments:
      - name: kubegame-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/version: 0.0.1-SNAPSHOT
              app.kubernetes.io/name: kubegame-operator
          template:
            metadata:
              annotations:
                app.quarkus.io/commit-id: b020027e12616727094de7401ad812b57d571d65
                app.quarkus.io/build-timestamp: 2023-04-08 - 22:52:49 +0000
                prometheus.io/scrape: "true"
                prometheus.io/path: /q/metrics
                prometheus.io/port: "8080"
                prometheus.io/scheme: http
              labels:
                app.kubernetes.io/version: 0.0.1-SNAPSHOT
                app.kubernetes.io/name: kubegame-operator
            spec:
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: mabulgu/kubegame-operator:0.0.1-SNAPSHOT
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                name: kubegame-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
              serviceAccountName: kubegame-operator
    strategy: deployment
  installModes:
  - supported: true
    type: AllNamespaces
